disabled_rules: # rule identifiers to exclude from running
- explicit_enum_raw_value
- array_init
- explicit_type_interface
- line_length
- nimble_operator
- no_grouping_extension
- notification_center_detachment
- attributes
- private_outlet
- private_over_fileprivate
- private_unit_test
- strict_fileprivate
- explicit_top_level_acl
- trailing_whitespace
- file_header
- unused_optional_binding
- trailing_closure
- switch_case_alignment
- let_var_whitespace
- cyclomatic_complexity
- trailing_comma

opt_in_rules: # some rules are only opt-in
- void_return
- first_where
- number_separator
- block_based_kvo
- class_delegate_protocol
- closing_brace
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- colon
- comma
- compiler_protocol_init
- conditional_returns_on_newline
- contains_over_first_not_nil
- control_statement
- discarded_notification_center_observer
- discouraged_direct_init
- dynamic_inline
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- explicit_init
- fallthrough
- fatal_error_message
- file_length
- for_where
- force_cast
- force_try
- force_unwrapping
- function_body_length
- function_parameter_count
- generic_type_name
- identifier_name
- implicit_getter
- implicit_return
- implicitly_unwrapped_optional
- is_disjoint
- joined_default_parameter
- large_tuple
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_nsgeometry_functions
- literal_expression_end_indentation
- mark
- multiline_arguments
- multiline_parameters
- multiple_closures_with_trailing_closure
- nesting
- object_literal
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- protocol_property_accessors_order
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_optional_initialization
- redundant_string_enum_value
- redundant_void_return
- return_arrow_whitespace
- shorthand_operator
- single_test_class
- sorted_imports
- statement_position
- superfluous_disable_command
- switch_case_on_newline
- syntactic_sugar
- todo
- trailing_newline
- trailing_semicolon
- type_body_length
- type_name
- unneeded_break_in_switch
- unneeded_parentheses_in_closure_argument
- unused_closure_parameter
- unused_enumerated
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace
- weak_delegate
- xctfail_message

# Rules configuration

closure_spacing:
  severity: error

colon:
   severity: error

force_unwrapping:
  severity: warning

force_cast:
  severity: warning

force_try:
  severity: warning

control_statement:
  severity: warning

cyclomatic_complexity:
  warning: 10
  error: 20

explicit_init:
  severity: error

file_length:
  warning: 400
  error: 800

first_where:
  severity: error

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 8
  error: 10

generic_type_name:
  min_length:
    warning: 0
    error: 1
  max_length:
    warning: 80
    error: 100

identifier_name:
  min_length:
    warning: 0
    error: 1
  max_length:
    warning: 80
    error: 100

implicitly_unwrapped_optional:
  severity: error

large_tuple:
  warning: 4
  error: 6

leading_whitespace:
  severity: error

legacy_cggeometry_functions:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

legacy_nsgeometry_functions:
  severity: error

#line_length:
#    warning: 140
#    error: 140

mark:
  severity: warning

nesting:
  severity: warning

notification_center_detachment:
  severity: error

number_separator:
  severity: error

object_literal:
  severity: error

opening_brace:
  severity: error

operator_whitespace:
  severity: error

operator_usage_whitespace:
  severity: error

overridden_super_call:
  severity: error

private_outlet:
  severity: error

private_unit_test:
  severity: error

prohibited_super_call:
  severity: error

redundant_nil_coalescing:
  severity: error

redundant_void_return:
  severity: error

return_arrow_whitespace:
  severity: error

shorthand_operator:
  severity: error

sorted_imports: error

statement_position:
  statement_mode: default
 #statement_mode: uncuddled_else
  severity: error

switch_case_on_newline:
  severity: error

syntactic_sugar:
  severity: error

trailing_comma:
  severity: error

trailing_newline: error

trailing_semicolon:
  severity: error

type_body_length:
  warning: 400
  error: 400

type_name:
  min_length:
    warning: 0
    error: 3
  max_length:
    warning: 80
    error: 100

unused_closure_parameter:
  severity: error

unused_enumerated:
  severity: error

unused_optional_binding:
  severity: error

valid_ibinspectable:
  severity: error

vertical_parameter_alignment:
  severity: error

vertical_whitespace:
  severity: error

weak_delegate:
  severity: error

reporter: "xcode"

# Find all the available rules by running:
# swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
- ./SwipeableTabBarController
- ./SwipeableTabBarControllerUITests
- ../SwipeableTabBarController/Classes
