default_platform(:ios)

platform :ios do

  desc "Release a new version of the pod"
  lane :release do
    pod_lib_lint
    version = version_bump_podspec(path: "SwipeableTabBarController.podspec", bump_type: "patch")
    git_add(path: "./SwipeableTabBarController.podspec")
    git_commit(path: ["./SwipeableTabBarController.podspec"], message: "#{version} release")
    changelog_from_git_commits(pretty: "- (%ae) %s", include_merges: false)
    add_git_tag(
  		tag: "#{version}"
	)
    push_to_git_remote
    pod_push
  end
end
