name: iOS Build and Test

on: pull_request

jobs:
  build:
    name: Build and Test using iPhone 11 Pro simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: set -o pipefail && xcodebuild -project Example.xcodeproj -scheme Example -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4" test | xcpretty --color